<head>
  <style>

  </style>
</head>

<body>
  <main id="home">
    <aside id="aside">
      <div class="container">
        <div class="logo-box">
          <img src="/img/Imagem.png" alt="logo-magazine esperança">
          <p class="name-logo">Magazine
          <p class="segundo-name-logo"> Esperança</p>
          </p>
          <form class="form-search" action="">
            <input class="input-search" type="search" placeholder="Busque seu produto aqui...">
            <div class="sarch-icon">
              <i class="material-symbols-outlined">
                search
              </i>
            </div>
          </form>
          <div class="user-box">
            <a href="/entrar" class="material-symbols-outlined">
              account_circle
            </a>
          </div>
          <div class="shopping-box">
            <a href="#" class="material-symbols-outlined">
              shopping_bag
            </a>
          </div>
        </div>
        <div class="nav">
          <div class="categoria">
            <i class="material-symbols-outlined">
              menu
            </i>
            <h4>categoria</h4>
          </div>
          <ul class="nav-link">
            <li><a href="#home">Home</a></li>
            <li><a class="actived" href="#produto">Produtos</a></li>
            <li><a href="#sobre-nos">Sobre</a></li>
          </ul>
        </div>
      </div>
    </aside>
    <section class="produto">
      <div class="container-pag-produto">
        <div class="area-produto">
          <div class="area-produto-img">
            <img src="img/69825_2_3.jpg" alt="produto">
          </div>
          <div class="area-produto-info">
            <div class="info-pag-produto">
              <p>Esfoliante Ekos</p>
              <p>Natura</p>
              <p>Cod. 119165 - Esfoliante Ekos - 200g</p>
              <p>R$ 150,90</p>
              <p>R$ 99,99</p>
              <p>À vista ou até 3x de 33,30 sem juros</p>
            </div>
            <div class="produto-comprar">
              <div data-app="product.quantity" id="quantidade">
                <span id="span_erro_carrinho" class="blocoAlerta" style="display:none;">Selecione uma opção para
                  variação do produto</span>
                <input type="button" id="plus" value='-' onclick="process(-1)" />
                <input id="quant" name="quant" class="text" size="1" type="text" value="1" maxlength="5" />
                <input type="button" id="minus" value='+' onclick="process(1)">
              </div>
              <div class="button-comprar">
                <a href="">
                  <div class="description-tela-produto-botton">
                    <p>COMPRE AGORA</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </section>
    <section id="sobre-nos">
      <div class="container">
        <div class="card-sobre-nos">
          <div class="sn-info1">
            <h4>História e evolução da empresa</h4>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur numquam ut, architecto
              quae
              excepturi aliquam, veniam a id nam ipsam non quo cupiditate mollitia esse placeat tempore
              dignissimos, voluptatibus culpa! Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Architecto eius necessitatibus, harum laborum accusamus, iusto, quo illo cupiditate corrupti
              consequuntur optio minima odio consequatur velit! Voluptatibus delectus distinctio ab in.
              Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Ullam consequatur mollitia laboriosam
              dicta
              nam sapiente quidem. Iste rerum facere, libero molestiae quas repellat provident nesciunt
              aliquam nobis quos aspernatur corrupti!</p>
          </div>
          <div class="sn-info2">
            <h4>Sua loja de cosmético e beleza</h4>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur numquam ut, architecto
              quae
              excepturi aliquam, veniam a id nam ipsam non quo cupiditate mollitia esse placeat tempore
              dignissimos, voluptatibus culpa! Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Architecto eius necessitatibus, harum laborum accusamus, iusto, quo illo cupiditate corrupti
              consequuntur optio minima odio consequatur velit! Voluptatibus delectus distinctio ab in.
              Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Ullam consequatur mollitia laboriosam
              dicta
              nam sapiente quidem. Iste rerum facere, libero molestiae quas repellat provident nesciunt
              aliquam nobis quos aspernatur corrupti!</p>
          </div>
        </div>

      </div>
    </section>
  </main>
</body>