<body id="entrar">
  <main>
    <header class="page-header">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <div class="logo">
        <img src="/img/Imagem.png" alt="logo-magazine esperança">
      </div>
    </header>
    <section id="main-section">
      <div class="container-card-form">
        <form class="subscribe-form" action="">
          <label class="label" for="email"> Email
            <input class="field-input" type="email" name="email" id="email" placeholder="Insira seu Email">
          </label>
          <label class="label" for="password"> Senha
            <input class="field-input" type="password" name="senha" id="password" placeholder="ex: ▪▪▪▪▪▪▪▪▪▪▪▪▪">
          </label>
          <button type="submit" class="btn btn-success btn-lg btn-block mb-3"
            style="background-color: #53C600; border-color: #53C600; width: 100%; border-radius: 2px;">Login</button>
          <a class="create-account-button" href="/inscreverse">Criar conta</a>
        </form>
      </div>
    </section>
  </main>
</body>