<body id="entrar">
  <main>
    <header class="page-header">
      <div class="logo">
        <a href="/">
          <img src="/img/Imagem.png" alt="logo-magazine esperança">
        </a>
      </div>
    </header>
    <section id="main-section">
      <div class="container-card-form">
        <form class="subscribe-form" action="/autenticar" method="post">
          <label class="label" for="email"> Email
            <input class="field-input" type="email" name="email" id="email" placeholder="Insira seu Email">
          </label>
          <label class="label" for="password"> Senha
            <input class="field-input" type="password" name="senha" id="password" placeholder="ex: ▪▪▪▪▪▪▪▪▪▪▪▪▪">
          </label>
          <button type="submit" class="btn btn-success btn-lg btn-block mb-3"
            style="background-color: #53C600; border-color: #53C600; width: 100%; border-radius: 2px;">Login</button>
          <a class="create-account-button" href="/inscreverse">Criar conta</a>
        </form>
      </div>
    </section>
  </main>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css" />
  <script src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

  <?php if ($this->view->login == 'erro') : ?>
  <script>
  Toastify({
    text: "Credenciais inválidas. Tente novamente",
    duration: 5000,
    close: true,
    gravity: "top",
    position: "right",
    backgroundColor: "#FFA500",
    className: "custom-toast",
  }).showToast();
  </script>
  <?php endif; ?>

  <?php if ($this->view->login == 'erroAutenticar') : ?>
  <script>
  Toastify({
    text: "Por favor, insira seu usuário e senha para continuar",
    duration: 5000,
    close: true,
    gravity: "top",
    position: "right",
    backgroundColor: "#4169E1",
    className: "custom-toast",
  }).showToast();
  </script>
  <?php endif; ?>
</body>