<body id="entrar">
  <main>
    <header class="page-header">
      <div class="logo">
        <a href="/">
          <img src="/img/Imagem.png" alt="logo-magazine esperança">
        </a>
      </div>
    </header>
    <section id="main-section">
      <div class="container-card-form">
        <form class="subscribe-form" action="">
          <label class="label" for="email"> Email
            <input class="field-input" type="email" name="email" id="email" placeholder="Insira seu Email">
          </label>
          <label class="label" for="password"> Senha
            <input class="field-input" type="password" name="senha" id="password" placeholder="ex: ▪▪▪▪▪▪▪▪▪▪▪▪▪">
          </label>
          <button type="submit" class="btn btn-success btn-lg btn-block mb-3"
            style="background-color: #53C600; border-color: #53C600; width: 100%; border-radius: 2px;">Login</button>
          <a class="create-account-button" href="/inscreverse">Criar conta</a>
        </form>
      </div>
    </section>
  </main>
</body>