<!doctype html>
<html lang="pt-BR">

<body>
  <main id="home">
    <aside id="aside">
      <div class="container">
        <div class="logo-box">
          <img src="/img/Imagem.png" alt="logo-magazine esperança">
          <p class="name-logo">Magazine
          <p class="segundo-name-logo"> Esperança</p>
          </p>
          <form class="form-search" action="">
            <input class="input-search" type="search" placeholder="Busque seu produto aqui...">
            <div class="sarch-icon">
              <i class="material-symbols-outlined">
                search
              </i>
            </div>
          </form>
          <div class="user-box">
            <a href="/entrar" class="material-symbols-outlined">
              account_circle
            </a>
          </div>
          <div class="shopping-box">
            <a href="#" class="material-symbols-outlined">
              shopping_bag
            </a>
          </div>
        </div>
        <div class="nav">
          <div class="categoria">
            <i class="material-symbols-outlined">
              menu
            </i>
            <h4>categoria</h4>
          </div>
          <ul class="nav-link">
            <li><a class="actived" href="#home">Home</a></li>
            <li><a href="#produto">Produtos</a></li>
            <li><a href="#sobre-nos">Sobre</a></li>
          </ul>
        </div>
      </div>
    </aside>
    <section class="banner">
      <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
              aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
              aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
              aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"
              aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="2000">
              <img src="/img/banner/header_01_4.jpg" class="d-block w-100" alt="banner1">
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="/img/banner/header_02_4.jpg" class="d-block w-100" alt="banner2">
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="/img/banner/header_03_4.jpg" class="d-block w-100" alt="banner3">
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="/img/banner/header_05_0.jpg" class="d-block w-100" alt="banner3">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </section>
    <section class="container-produto" id="produto">
      <div class="container">
        <div class="card-produto">
          <div class="produto1">
            <div class="produto-info">
              <h3 class="produto-title">Óleo Trifásico Buriti</h3>
              <p class="description-produto">Cod. 112087 - Óleo Trifásico Desodorante Corporal Ekos Buriti
                - 200 ml</p>
              <a class="link-produto" href="">Compre agora</a>
            </div>
            <div class="img-produto">
              <img src="img/112087_1_8-removebg-preview.png" alt="produto1">
            </div>
          </div>
          <div class="produto1">
            <div class="produto-info">
              <h3 class="produto-title">Óleo Trifásico Buriti</h3>
              <p class="description-produto">Cod. 112087 - Óleo Trifásico Desodorante Corporal Ekos Buriti
                - 200 ml</p>
              <a class="link-produto" href="">Compre agora</a>
            </div>
            <div class="img-produto">
              <img src="img/112087_1_8-removebg-preview.png" alt="produto1">
            </div>
          </div>
          <div class="produto1">
            <div class="produto-info">
              <h3 class="produto-title">Óleo Trifásico Buriti</h3>
              <p class="description-produto">Cod. 112087 - Óleo Trifásico Desodorante Corporal Ekos Buriti
                - 200 ml</p>
              <a class="link-produto" href="">Compre agora</a>
            </div>
            <div class="img-produto">
              <img src="img/112087_1_8-removebg-preview.png" alt="produto1">
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="opcoes-filtro-produtos">
      <div class="container">
        <div class="container-filtro-produtos">
          <a href="#">
            <div class="opcao-filtro">
              <p class="titulo-filtro">Mais Vendidos</p>
            </div>
          </a>
          <a href="#">
            <div class="opcao-filtro">
              <p class="titulo-filtro">Novidades</p>
            </div>
          </a>
          <a href="#">
            <div class="opcao-filtro">
              <p class="titulo-filtro">Melhores Avaliados</p>
            </div>
          </a>
        </div>
      </div>
    </section>

    <section class="produtos">
      <div class="container">
        <div class="card-produto-two">
          <?php foreach($this->view->produtos as $ID_Prod => $produto) { ?>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="img/69825_2_3.jpg" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3><?= $produto['modelo'] ?></h3>
                <p class="description-produto-two-preço">R$<?= $produto['valor'] ?></p>
                <p>ou <?= $produto['valor_parcelado']?></p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <p>Compre agora</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <?php } ?>
        </div>
    </section>


    <section id="sobre-nos">
      <div class="container">
        <div class="card-sobre-nos">
          <div class="sn-info1">
            <h4>História e evolução da empresa</h4>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur numquam ut, architecto
              quae
              excepturi aliquam, veniam a id nam ipsam non quo cupiditate mollitia esse placeat tempore
              dignissimos, voluptatibus culpa! Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Architecto eius necessitatibus, harum laborum accusamus, iusto, quo illo cupiditate corrupti
              consequuntur optio minima odio consequatur velit! Voluptatibus delectus distinctio ab in.
              Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Ullam consequatur mollitia laboriosam
              dicta
              nam sapiente quidem. Iste rerum facere, libero molestiae quas repellat provident nesciunt
              aliquam nobis quos aspernatur corrupti!</p>
          </div>
          <div class="sn-info2">
            <h4>Sua loja de cosmético e beleza</h4>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Consectetur numquam ut, architecto
              quae
              excepturi aliquam, veniam a id nam ipsam non quo cupiditate mollitia esse placeat tempore
              dignissimos, voluptatibus culpa! Lorem ipsum dolor sit amet consectetur, adipisicing elit.
              Architecto eius necessitatibus, harum laborum accusamus, iusto, quo illo cupiditate corrupti
              consequuntur optio minima odio consequatur velit! Voluptatibus delectus distinctio ab in.
              Lorem
              ipsum dolor sit amet consectetur adipisicing elit. Ullam consequatur mollitia laboriosam
              dicta
              nam sapiente quidem. Iste rerum facere, libero molestiae quas repellat provident nesciunt
              aliquam nobis quos aspernatur corrupti!</p>
          </div>
        </div>

      </div>
    </section>
  </main>
</body>

</html>