<!doctype html>
<html lang="pt-BR">

<body>
  <main>
    <header id="header">
      <div class="container">
        <div class="logo-box">
          <img src="/img/Imagem.png" alt="">
          <p class="name-logo">Magazine<span style="color: #8EE91A;"> Esperança</span></p>
          <form action="">
            <input type="text" placeholder="Busque seu produto aqui...">
          </form>
          <div class="sarch-icon">
            <i class="material-symbols-outlined">
              search
            </i>
          </div>
        </div>
        <div class="nav">
          <div class="categoria">
            <i class="material-symbols-outlined">
              menu
            </i>
            <h4>categoria</h4>
          </div>
          <ul>
            <li><a href="">Home</a></li>
            <li><a href="">Produtos</a></li>
            <li><a href="">Sobre</a></li>
          </ul>
        </div>
        <div class="user-box">

        </div>
      </div>
    </header>
    <section class="banner">
      <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
              aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
              aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
              aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"
              aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="2000">
              <img src="/img/banner/header_01_4.jpg" class="d-block w-100" alt="banner1">
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="/img/banner/header_02_4.jpg" class="d-block w-100" alt="banner2">
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="/img/banner/header_03_4.jpg" class="d-block w-100" alt="banner3">
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="/img/banner/header_05_0.jpg" class="d-block w-100" alt="banner3">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </section>
    <section class="container-produto">
      <div class="container">
        <div class="card-produto">
          <div class="produto1">
            <div class="produto-info">
              <h3 class="produto-title">Óleo Trifásico Buriti</h3>
              <p class="description-produto">Cod. 112087 - Óleo Trifásico Desodorante Corporal Ekos Buriti
                - 200 ml</p>
              <a class="link-produto" href="">Compre agora</a>
            </div>
            <div class="img-produto">
              <img src="img/112087_1_8-removebg-preview.png" alt="produto1">
            </div>
          </div>
          <div class="produto1">
            <div class="produto-info">
              <h3 class="produto-title">Óleo Trifásico Buriti</h3>
              <p class="description-produto">Cod. 112087 - Óleo Trifásico Desodorante Corporal Ekos Buriti
                - 200 ml</p>
              <a class="link-produto" href="">Compre agora</a>
            </div>
            <div class="img-produto">
              <img src="img/112087_1_8-removebg-preview.png" alt="produto1">
            </div>
          </div>
          <div class="produto1">
            <div class="produto-info">
              <h3 class="produto-title">Óleo Trifásico Buriti</h3>
              <p class="description-produto">Cod. 112087 - Óleo Trifásico Desodorante Corporal Ekos Buriti
                - 200 ml</p>
              <a class="link-produto" href="">Compre agora</a>
            </div>
            <div class="img-produto">
              <img src="img/112087_1_8-removebg-preview.png" alt="produto1">
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="opcoes-filtro-produtos">
      <div class="container">
        <div class="container-filtro-produtos">
          <a href="#">
            <div class="opcao-filtro">
              <p class="titulo-filtro">Mais Vendidos</p>
            </div>
          </a>
          <a href="#">
            <div class="opcao-filtro">
              <p class="titulo-filtro">Novidades</p>
            </div>
          </a>
          <a href="#">
            <div class="opcao-filtro">
              <p class="titulo-filtro">Melhores Avaliados</p>
            </div>
          </a>
        </div>
      </div>
    </section>
    <section class="produtos">
      <div class="container">
        <div class="card-produto-two">
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="img/69825_2_3.jpg" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3>Esfoliante Ekos</h3>
                <p class="description-produto-two-preço">R$157,00</p>
                <p>ou 3x R$52,34</p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <p>Compre agora</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="img/69825_2_3.jpg" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3>Esfoliante Ekos</h3>
                <p class="description-produto-two-preço">R$157,00</p>
                <p>ou 3x R$52,34</p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <p>Compre agora</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="img/69825_2_3.jpg" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3>Esfoliante Ekos</h3>
                <p class="description-produto-two-preço">R$157,00</p>
                <p>ou 3x R$52,34</p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <p>Compre agora</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="img/69825_2_3.jpg" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3>Esfoliante Ekos</h3>
                <p class="description-produto-two-preço">R$157,00</p>
                <p>ou 3x R$52,34</p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <p>Compre agora</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="img/69825_2_3.jpg" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3>Esfoliante Ekos</h3>
                <p class="description-produto-two-preço">R$157,00</p>
                <p>ou 3x R$52,34</p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <p>Compre agora</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="img/69825_2_3.jpg" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3>Esfoliante Ekos</h3>
                <p class="description-produto-two-preço">R$157,00</p>
                <p>ou 3x R$52,34</p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <p>Compre agora</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="img/69825_2_3.jpg" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3>Esfoliante Ekos</h3>
                <p class="description-produto-two-preço">R$157,00</p>
                <p>ou 3x R$52,34</p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <p>Compre agora</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="img/69825_2_3.jpg" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3>Esfoliante Ekos</h3>
                <p class="description-produto-two-preço">R$157,00</p>
                <p>ou 3x R$52,34</p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <p>Compre agora</p>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
</body>

</html>