<body id="inscreverse">
  <main>
    <header class="page-header">
      <div class="logo">
        <img src="/img/Imagem.png" alt="logo-magazine esperança">
      </div>
    </header>
    <section id="main-section">

      <div class="container-card-form">
        <form class="subscribe-form" action="">
          <label class="label" for="email"> Email
            <input class="field-input" type="email" name="email" id="email" placeholder="Insira sei Email">
          </label>
          <label class="label" for="password"> Senha
            <input class="field-input" type="password" name="senha" id="password" placeholder="ex: **********">
          </label>
          <button class="login-button" type="submit">Entrar</button>
          <hr>
          <button class="create-account-button" href="#">Criar conta</button>
        </form>
      </div>


    </section>
  </main>
</body>