<!doctype html>
<html lang="pt-BR">

<body>
  <aside id="aside">
    <div class="container">
      <div class="logo-box">
        <a class="logo" href="/timeline">
          <img src="/img/Imagem.png" alt="logo-magazine esperança">
          <p class="name-logo">Magazine
            <p class="segundo-name-logo"> Esperança</p>
        </a>
        </p>
        <form id="pesquisarProduto" class="form-search">
          <input id="buscarProduto" name="pesquisar" class="input-search" type="search"
            placeholder="Busque seu produto aqui...">
          <div class="sarch-icon">
            <i class="material-symbols-outlined">
              search
            </i>
          </div>
        </form>
        <div class="logout-acount">
          <a href="/sair" class="">
            <span id="logout-box" class="material-symbols-outlined">logout</span>
            <?php foreach($this->view->usuario as $user) { ?>
            <p>Olá, <span><?= ucfirst($user['nome']).' '.ucfirst($user['sobrenome']) ?></span><br>Clique aqui para
              sair</p>
            <?php } ?>
          </a>
        </div>
        <div class="shopping-box">
          <a href="#" class="material-symbols-outlined">
            shopping_bag
          </a>
        </div>
      </div>
      <div class="nav">
        <div class="categoria">
          <i class="material-symbols-outlined">
            menu
          </i>
          <h4>categoria</h4>
        </div>
        <ul class="nav-link">
          <li><a href="/timeline">Home</a></li>
          <li><a href="/produtos?categoria=Perfumaria">Perfumaria</a></li>
          <li><a href="/produtos?categoria=Corpo e Banho">Corpo e Banho</a></li>
          <li><a href="/produtos?categoria=Cabelos">Cabelos</a></li>
          <li><a href="/produtos?categoria=Skincare">Skincare</a></li>
          <li><a href="/produtos?categoria=Maquiagem">Maquiagem</a></li>
          <li><a href="/produtos?categoria=Sobre">Sobre</a></li>
        </ul>
      </div>
    </div>
  </aside>

  <!-- FIM CABEÇALHO -->
  <main id="home">
    <section class="tela-produtos">
      <div class="container">
        <div class="card-produto-two">
          <?php foreach($this->view->produtoCategoria as $ID_Prod => $produto) { ?>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="<?= $produto['imgConvertida'] ?>" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3><?= $produto['modelo'] ?></h3>
                <p class="description-produto-two-preço">R$<?= $produto['valor'] ?></p>
                <p>ou <?= $produto['valor_parcelado']?></p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <a href="/produto?id=<?= $produto['ID_Prod'] ?>&marca=<?= $produto['marca'] ?>">
                      <p>Compre agora</p>
                    </a>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <?php } ?>
        </div>
    </section>

    <!-- INICIO RODAPÉ -->

    <section id="footer">
      <div class="container">
        <div class="footer-context">
          <div class="product-category">
            <h1>Produtos</h1>
            <a href="#">Perfumaria</a>
            <a href="#">Corpo e banho</a>
            <a href="#">Skin Care</a>
            <a href="#">Cabelos</a>
            <a href="#">Maquiagem</a>
          </div>
          <div class="product-category">
            <h1>Atendimento</h1>
            <p>
              <i class="material-symbols-outlined">phone</i>
              <a
                href="https://api.whatsapp.com/send?phone=5575981019016&text=Ol%C3%A1!%20Bem-vindo%20%C3%A0%20Magazine%20Esperan%C3%A7a,%20a%20sua%20loja%20de%20confian%C3%A7a.%20Agradecemos%20por%20entrar%20em%20contato%20conosco%20pelo%20WhatsApp.%20Nossa%20equipe%20de%20atendimento%20est%C3%A1%20pronta%20para%20ajud%C3%A1-lo(a).">
                (75) 98101-9016
              </a>
            </p>
            <p>
              <i class="material-symbols-outlined">mail</i>
              magazine.esperanca23@gmail.com
            </p>
          </div>
          <div class="product-category">
            <h1>Suporte</h1>
            <a href="#">Trocas e devoluções</a>
            <a href="#">Dúvidas</a>
            <a href="#">Cartão fidelidade</a>
            <a href="#">Faça parte da equipe</a>
          </div>
          <div class="product-category-social-network">
            <a href="http://">
              <i class="fa-brands fa-facebook" style="color: #ffffff;"></i>
            </a>
            <a href="https://www.instagram.com/magazine_esperanca/">
              <i class="fa-brands fa-instagram" style="color: #ffffff;"></i>
            </a>
            <a href="http://">
              <i class="fa-brands fa-telegram" style="color: #ffffff;"></i>
            </a>
          </div>
        </div>
        <div class="copy">
          <h1>&copy 2023 Magazine Esperança. Todos os direitos reservados.</h1>
        </div>
      </div>
    </section>
  </main>
</body>

</html>