<!doctype html>
<html lang="pt-BR">

<body>
  <aside id="aside">
    <div class="container">
      <div class="logo-box">
        <a class="logo" href="/timeline">
          <img src="/img/Imagem.png" alt="logo-magazine esperança">
          <p class="name-logo">Magazine
            <p class="segundo-name-logo"> Esperança</p>
        </a>
        </p>
        <form id="pesquisarProduto" class="form-search">
          <input id="buscarProduto" name="pesquisar" class="input-search" type="search"
            placeholder="Busque seu produto aqui...">
          <div class="sarch-icon">
            <i class="material-symbols-outlined">
              search
            </i>
          </div>
        </form>
        <div class="logout-acount">
          <a href="/sair" class="">
            <span id="logout-box" class="material-symbols-outlined">logout</span>
            <?php foreach($this->view->usuario as $user) { ?>
            <p>Olá, <span><?= ucfirst($user['nome']).' '.ucfirst($user['sobrenome']) ?></span><br>Clique aqui para
              sair</p>
            <?php } ?>
          </a>
        </div>
        <div class="shopping-box">
          <a href="#" class="material-symbols-outlined">
            shopping_bag
          </a>
        </div>
      </div>
      <div class="nav">
        <div class="categoria">
          <i class="material-symbols-outlined">
            menu
          </i>
          <h4>categoria</h4>
        </div>
        <ul class="nav-link">
          <li><a class="actived" href="#home">Home</a></li>
          <li><a href="/produtos">Produtos</a></li>
          <li><a href="#sobre-nos">Perfumaria</a></li>
          <li><a href="#sobre-nos">Corpo e Banho</a></li>
          <li><a href="#sobre-nos">Cabelos</a></li>
          <li><a href="#sobre-nos">Skincare</a></li>
          <li><a href="#sobre-nos">Maquiagem</a></li>
          <li><a href="#sobre-nos">Sobre</a></li>
        </ul>
      </div>
    </div>
  </aside>
  <main id="home">
    <section class="banner">
      <div class="container">
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
              aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
              aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
              aria-label="Slide 3"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="3"
              aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="2000">
              <img src="/img/banner/header_01_4.jpg" class="d-block w-100" alt="banner1">
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="/img/banner/header_02_4.jpg" class="d-block w-100" alt="banner2">
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="/img/banner/header_03_4.jpg" class="d-block w-100" alt="banner3">
            </div>
            <div class="carousel-item" data-bs-interval="2000">
              <img src="/img/banner/header_05_0.jpg" class="d-block w-100" alt="banner3">
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </section>
    <section class="container-produto" id="produto">
      <div class="container">
        <div class="card-produto">
          <?php foreach($this->view->produtosThree as $ID_Prod => $produtosThree) { ?>
          <div class="produto1">
            <div class="produto-info">
              <h3 class="produto-title"><?= $produtosThree['modelo'] ?></h3>
              <p class="description-produto"><?= $produtosThree['Descrição_curta'] ?></p>
              <a class="link-produto"
                href="/produto?id=<?= $produtosThree['ID_Prod'] ?>&marca=<?= $produtosThree['marca'] ?>">Compre
                agora</a>
            </div>
            <div class="img-produto">
              <img src="<?= $produtosThree['imgConvertida'] ?>" alt="produto1">
            </div>
          </div>
          <?php } ?>
        </div>
      </div>
    </section>
    <section class="opcoes-filtro-produtos">
      <div class="container">
        <div class="container-filtro-produtos">
          <a href="#">
            <div class="opcao-filtro">
              <p class="titulo-filtro">Mais Vendidos</p>
            </div>
          </a>
          <a href="#">
            <div class="opcao-filtro">
              <p class="titulo-filtro">Novidades</p>
            </div>
          </a>
          <a href="#">
            <div class="opcao-filtro">
              <p class="titulo-filtro">Melhores Avaliados</p>
            </div>
          </a>
        </div>
      </div>
    </section>
    <section class="produtos">
      <div class="container">
        <div class="card-produto-two">
          <?php foreach($this->view->produtos as $ID_Prod => $produto) { ?>
          <div class="produto-two">
            <div class="informacao-produto">
              <div class="imagem-produto">
                <img src="<?= $produto['imgConvertida'] ?>" alt="Imagem do produto 1">
              </div>
              <div class="description-produto-two">
                <h3><?= $produto['modelo'] ?></h3>
                <p class="description-produto-two-preço">R$<?= $produto['valor'] ?></p>
                <p>ou <?= $produto['valor_parcelado']?></p>
                <a href="">
                  <div class="description-produto-two-botton">
                    <a href="/produto?id=<?= $produto['ID_Prod'] ?>&marca=<?= $produto['marca'] ?>">
                      <p>Compre agora</p>
                    </a>
                  </div>
                </a>
              </div>
            </div>
          </div>
          <?php } ?>
        </div>
    </section>
    <section id="sobre-nos">
      <div class="container">
        <div class="card-sobre-nos">
          <div class="sn-info1">
            <h4>História e evolução da empresa</h4>
            <p>Começamos como uma consultora de perfumes nos tornando lideres de vendas, cadastramos consultores e
              abrimos uma pequena loja
              em
              casa. continuamos liderando até abrir uma loja na galeria. focados no crescimento, a loja
              cresceu e se tornou referência em perfumaria, com variedade e qualidade. A história inspira a transformar
              paixão em negócio de sucesso.</p>
          </div>
          <div class="sn-info2">
            <h4>Sua loja de cosmético e beleza</h4>
            <p>Aqui, oferecemos uma ampla variedade de produtos das marcas mais renomadas, incluindo Avon, Natura, O
              Boticário, Hinode, Eudora e muitas outras. Como uma das maiores empresas de perfumaria da região, estamos
              comprometidos em fornecer aos nossos clientes uma experiência excepcional.</p>
          </div>
        </div>
      </div>
    </section>
    <section id="img-banner">
      <img src="img/namorados-home-opções-presentes-desk_0.png" alt="">
    </section>
    <section id="footer">
      <div class="container">
        <div class="footer-context">
          <div class="product-category">
            <h1>Produtos</h1>
            <a href="#">Perfumaria</a>
            <a href="#">Corpo e banho</a>
            <a href="#">Skin Care</a>
            <a href="#">Cabelos</a>
            <a href="#">Maquiagem</a>
          </div>
          <div class="product-category">
            <h1>Atendimento</h1>
            <p>
              <i class="material-symbols-outlined">phone</i>
              <a
                href="https://api.whatsapp.com/send?phone=5575981019016&text=Ol%C3%A1!%20Bem-vindo%20%C3%A0%20Magazine%20Esperan%C3%A7a,%20a%20sua%20loja%20de%20confian%C3%A7a.%20Agradecemos%20por%20entrar%20em%20contato%20conosco%20pelo%20WhatsApp.%20Nossa%20equipe%20de%20atendimento%20est%C3%A1%20pronta%20para%20ajud%C3%A1-lo(a).">
                (75) 98101-9016
              </a>
            </p>
            <p>
              <i class="material-symbols-outlined">mail</i>
              magazine.esperanca23@gmail.com
            </p>
          </div>
          <div class="product-category">
            <h1>Suporte</h1>
            <a href="#">Trocas e devoluções</a>
            <a href="#">Dúvidas</a>
            <a href="#">Cartão fidelidade</a>
            <a href="#">Faça parte da equipe</a>
          </div>
          <div class="product-category-social-network">
            <a href="http://">
              <i class="fa-brands fa-facebook" style="color: #ffffff;"></i>
            </a>
            <a href="https://www.instagram.com/magazine_esperanca/">
              <i class="fa-brands fa-instagram" style="color: #ffffff;"></i>
            </a>
            <a href="http://">
              <i class="fa-brands fa-telegram" style="color: #ffffff;"></i>
            </a>
          </div>
        </div>
        <div class="copy">
          <h1>&copy 2023 Magazine Esperança. Todos os direitos reservados.</h1>
        </div>
      </div>
    </section>
  </main>
</body>

</html>